apiVersion: v1
kind: Service
metadata:
  name: telegram-notifier
spec:
  selector:
    app: telegram-notifier
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-notifier
  labels:
    app: telegram-notifier
spec:
  selector:
    matchLabels:
      app: telegram-notifier
  replicas: 1
  template:
    metadata:
      labels:
        app: telegram-notifier
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: registry.ignacioyeli.es/telegram-notifier:1.0.0
          name: telegram-notifier
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: NOTIFIER_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram
                  key: token
          ports:
            - containerPort: 8081
              name: http
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: telegram-notifier
  labels:
    app: telegram-notifier
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telegram-notifier
  targetCPUUtilizationPercentage: 70
